package frc.robot.Auton;

import com.pathplanner.lib.path.GoalEndState;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.path.PathPlannerPath;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.RobotContainer;

/**
 * Drive forward a short distance relative to the robot's current pose. The path is generated at
 * runtime (when the InstantCommand runs) so it uses the robot's actual pose at the start of
 * autonomous instead of the pose at program startup.
 */
public class Forward2m extends AutonCommandBase {

  private static final double DISTANCE_METERS = 2.0;
  private static final double MAX_VEL = 1.0; // m/s
  private static final double MAX_ACCEL = 1.0; // m/s²
  private static final double MAX_ANGULAR_VEL = 540.0; // deg/s
  private static final double MAX_ANGULAR_ACCEL = 720.0; // deg/s²

  public Forward2m(RobotContainer robotContainer) {
    // No starting rotation reset — let this auto run from wherever the robot actually is.
    super(robotContainer, null);

    // InstantCommand will run at the start of auto and schedule the generated follow-path
    // command. This avoids using the robot pose at program start.
    this.addCommands(
        new InstantCommand(
            () -> {
              Pose2d currentPose = robotContainer.getDrive().getPose();

              double theta = currentPose.getRotation().getRadians();
              double dx = DISTANCE_METERS * Math.cos(theta);
              double dy = DISTANCE_METERS * Math.sin(theta);
              Translation2d offset = new Translation2d(dx, dy);
              Pose2d targetPose =
                  new Pose2d(currentPose.getTranslation().plus(offset), currentPose.getRotation());

              PathPlannerPath path =
                  new PathPlannerPath(
                      PathPlannerPath.waypointsFromPoses(currentPose, targetPose),
                      new PathConstraints(MAX_VEL, MAX_ACCEL, MAX_ANGULAR_VEL, MAX_ANGULAR_ACCEL),
                      null,
                      new GoalEndState(0.0, currentPose.getRotation()));

              // Don't let PathPlanner flip this short, robot-relative path.
              path.preventFlipping = true;

              // Schedule the follow-path command generated by our helper.
              CommandScheduler.getInstance().schedule(followPath(path));
            }));
  }
}
