// Copyright (c) 2021-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by a BSD
// license that can be found in the LICENSE file
// at the root directory of this project.

package frc.robot;

import com.pathplanner.lib.auto.AutoBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.lib.subsystems.TalonFXIO;
import frc.robot.commands.DriveCommands;
import frc.robot.generated.TunerConstants;
// TODO: Fix Shooter class - package frc.robot.subsystems.CoralShooter does not exist
// import frc.robot.subsystems.CoralShooter.Shooter;
// TODO: Re-enable these subsystems once MotorInputsAutoLogged is generated
// import frc.robot.subsystems.scorer.flywheel.Flywheel;
// import frc.robot.subsystems.scorer.hood.Hood;
import frc.robot.subsystems.agitator.Agitator;
import frc.robot.subsystems.drive.Drive;
import frc.robot.subsystems.drive.GyroIO;
import frc.robot.subsystems.drive.GyroIOPigeon2;
import frc.robot.subsystems.drive.ModuleIO;
import frc.robot.subsystems.drive.ModuleIOSim;
import frc.robot.subsystems.drive.ModuleIOTalonFX;
import frc.robot.subsystems.intake.IntakePivot;
import frc.robot.subsystems.intake.IntakeRollers;
import org.littletonrobotics.junction.networktables.LoggedDashboardChooser;

/**
 * This class is where the bulk of the robot should be declared. Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of the robot (including
 * subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {
  // Subsystems
  private final Drive drive;
  // private final Intake intake;
  //

  // TODO: Re-enable these subsystems once MotorInputsAutoLogged is generated by AdvantageKit
  private IntakePivot intakePivot;
  // private final Hood hood;
  // private final Flywheel flywheel;
  private final Agitator agitatorRight;
  private final Agitator agitatorLeft;
  private final Agitator verticalFeedRight;
  private final Agitator verticalFeedLeft;
  private IntakeRollers intakeRollers;
  // private final Shooter shooter;

  // Autonomous commands
  private final frc.robot.Auton.AutonCommandBase autonCommands;

  // Controller
  private final CommandXboxController controller = new CommandXboxController(0);

  // Dashboard inputs
  private final LoggedDashboardChooser<Command> autoChooser;

  /** The container for the robot. Contains subsystems, OI devices, and commands. */
  public RobotContainer() {
    switch (Constants.currentMode) {
      case REAL:
        // Real robot, instantiate hardware IO implementations
        // ModuleIOTalonFX is intended for modules with TalonFX drive, TalonFX turn, and
        // a CANcoder
        drive =
            new Drive(
                new GyroIOPigeon2(),
                new ModuleIOTalonFX(TunerConstants.FrontLeft),
                new ModuleIOTalonFX(TunerConstants.FrontRight),
                new ModuleIOTalonFX(TunerConstants.BackLeft),
                new ModuleIOTalonFX(TunerConstants.BackRight));

        // The ModuleIOTalonFXS implementation provides an example implementation for
        // ModuleIOTalonFXS controller connected to a CANdi with a PWM encoder. The
        // implementations
        // of ModuleIOTalonFX, ModuleIOTalonFXS, and ModuleIOSpark (from the Spark
        // swerve
        // template) can be freely intermixed to support alternative hardware
        // arrangements.
        // Please see the AdvantageKit template documentation for more information:
        // https://docs.advantagekit.org/getting-started/template-projects/talonfx-swerve-template#custom-module-implementations
        //
        // drive =
        // new Drive(
        // new GyroIOPigeon2(),
        // new ModuleIOTalonFXS(TunerConstants.FrontLeft),
        // new ModuleIOTalonFXS(TunerConstants.FrontRight),
        // new ModuleIOTalonFXS(TunerConstants.BackLeft),
        // new ModuleIOTalonFXS(TunerConstants.BackRight));

        // Intake subsystem - Motor ID 58
        // intake = new Intake(new IntakeIOTalonFX(58, TunerConstants.kCANBus1));
        intakeRollers =
            new IntakeRollers(
                Constants.kIntakeRollerConfig,
                new TalonFXIO(Constants.kIntakeRollerConfig),
                new TalonFXIO[] {new TalonFXIO(Constants.kIntakeRollerConfig.followers[0].config)});
        intakePivot =
            new IntakePivot(
                Constants.kIntakePivotConfig, new TalonFXIO(Constants.kIntakePivotConfig));

        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // hood = new Hood(Constants.kHoodConfig, new TalonFXIO(Constants.kHoodConfig));

        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // flywheel =
        //     new Flywheel(Constants.kFlywheelConfig, new TalonFXIO(Constants.kFlywheelConfig));
        agitatorRight =
            new Agitator(
                Constants.kRightFloorRollerConfig,
                new TalonFXIO(Constants.kRightFloorRollerConfig));
        agitatorLeft =
            new Agitator(
                Constants.kLeftFloorRollerConfig, new TalonFXIO(Constants.kLeftFloorRollerConfig));
        verticalFeedRight =
            new Agitator(
                Constants.kRightVerticalFeedConfig,
                new TalonFXIO(Constants.kRightVerticalFeedConfig));
        verticalFeedLeft =
            new Agitator(
                Constants.kLeftVerticalFeedConfig,
                new TalonFXIO(Constants.kLeftVerticalFeedConfig));
        break;

      case SIM:
        // Sim robot, instantiate physics sim IO implementations
        drive =
            new Drive(
                new GyroIO() {},
                new ModuleIOSim(TunerConstants.FrontLeft),
                new ModuleIOSim(TunerConstants.FrontRight),
                new ModuleIOSim(TunerConstants.BackLeft),
                new ModuleIOSim(TunerConstants.BackRight));
        // intake = new Intake(new IntakeIO() {});
        // intakeRollers =
        //     new IntakeRollers(
        //         Constants.kIntakeRollerConfig, new SimTalonFXIO(Constants.kIntakeRollerConfig));
        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // intakePivot =
        //     new IntakePivot(
        //         Constants.kIntakePivotConfig, new SimTalonFXIO(Constants.kIntakePivotConfig));
        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // shooter = new Shooter(Constants.kShooterConfig, new
        // SimTalonFXIO(Constants.kShooterConfig));
        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // hood = new Hood(Constants.kHoodConfig, new SimTalonFXIO(Constants.kHoodConfig));
        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // flywheel =
        //     new Flywheel(Constants.kFlywheelConfig, new SimTalonFXIO(Constants.kFlywheelConfig));
        agitatorRight = null;
        agitatorLeft = null;
        verticalFeedRight = null;
        verticalFeedLeft = null;
        break;

      default:
        // Replayed robot, disable IO implementations
        drive =
            new Drive(
                new GyroIO() {},
                new ModuleIO() {},
                new ModuleIO() {},
                new ModuleIO() {},
                new ModuleIO() {});
        // intake = new Intake(new IntakeIO() {});
        // intakeRollers = null;
        // TODO: Re-enable after AdvantageKit generates MotorInputsAutoLogged
        // intakePivot = null;
        // shooter = null;
        // hood = null;
        // flywheel = null;
        agitatorRight = null;
        agitatorLeft = null;
        verticalFeedRight = null;
        verticalFeedLeft = null;
        break;
    }

    // Initialize autonomous commands
    autonCommands = new frc.robot.Auton.AutonCommandBase(drive);

    // Set up auto routines
    autoChooser = new LoggedDashboardChooser<>("Auto Choices", AutoBuilder.buildAutoChooser());

    // Automatically register all autonomous commands from AutonCommandBase
    autonCommands.registerAllCommands(autoChooser);

    // Also manually add them as backup (for testing)
    autoChooser.addOption("Forward 2m (Manual)", autonCommands.forward2m());
    autoChooser.addOption("Example Auto (Manual)", autonCommands.exampleAuto());

    // Set up SysId routines
    autoChooser.addOption(
        "Drive Wheel Radius Characterization", DriveCommands.wheelRadiusCharacterization(drive));
    autoChooser.addOption(
        "Drive Simple FF Characterization", DriveCommands.feedforwardCharacterization(drive));
    autoChooser.addOption(
        "Drive SysId (Quasistatic Forward)",
        drive.sysIdQuasistatic(SysIdRoutine.Direction.kForward));
    autoChooser.addOption(
        "Drive SysId (Quasistatic Reverse)",
        drive.sysIdQuasistatic(SysIdRoutine.Direction.kReverse));
    autoChooser.addOption(
        "Drive SysId (Dynamic Forward)", drive.sysIdDynamic(SysIdRoutine.Direction.kForward));
    autoChooser.addOption(
        "Drive SysId (Dynamic Reverse)", drive.sysIdDynamic(SysIdRoutine.Direction.kReverse));

    // TODO: Re-enable after subsystems are fixed
    // Add SmartDashboard buttons for shooter (only if shooter exists)
    // if (shooter != null) {
    //   SmartDashboard.putData("Shooter: 3000 RPM", shooter.RPMCommand(3000.0));
    //   SmartDashboard.putData("Shooter: 4000 RPM", shooter.RPMCommand(4000.0));
    //   SmartDashboard.putData("Shooter: 5000 RPM", shooter.RPMCommand(5000.0));
    //   SmartDashboard.putData("Shooter: Stop", shooter.dutyCycleCommand(() -> 0.0));
    // }

    // Configure the button bindings
    configureButtonBindings();
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a {@link
   * edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
    // Default command, normal field-relative drive
    drive.setDefaultCommand(
        DriveCommands.joystickDrive(
            drive,
            () -> -controller.getLeftY(),
            () -> -controller.getLeftX(),
            () -> -controller.getRightX()));

    // Lock to 0° when A button is held
    controller
        .a()
        .whileTrue(
            DriveCommands.joystickDriveAtAngle(
                drive,
                () -> -controller.getLeftY(),
                () -> -controller.getLeftX(),
                () -> Rotation2d.kZero));

    // Switch to X pattern when X button is pressed
    controller.x().onTrue(Commands.runOnce(drive::stopWithX, drive));

    // Reset gyro to 0° when B button is pressed
    controller
        .b()
        .onTrue(
            Commands.runOnce(
                    () ->
                        drive.setPose(
                            new Pose2d(drive.getPose().getTranslation(), Rotation2d.kZero)),
                    drive)
                .ignoringDisable(true));

    // TODO: Re-enable after subsystems are fixed
    // Intake controls
    // Left Trigger - Run intake forward (hold to run forward)
    // controller.leftTrigger().whileTrue(intakePivot.setDegreesCommand(180));

    // Right Trigger - Run intake backward (hold to run backward)
    // controller.rightTrigger().whileTrue(intakePivot.setDegreesCommand(-180.0));

    // controller.leftBumper().whileTrue(hood.setDegreesCommand(0.0));

    // controller.rightBumper().whileTrue(hood.setDegreesCommand(15.0));

    // controller.rightBumper().whileTrue(flywheel.forwardCommand());

    if (agitatorRight != null && agitatorLeft != null) {
      // Y button = toggle agitator rollers on/off (closed loop PID)
      controller
          .y()
          .toggleOnTrue(
              Commands.parallel(agitatorRight.intakeCommand(), agitatorLeft.intakeCommand()));
    }

    if (verticalFeedRight != null && verticalFeedLeft != null) {
      // Left Trigger = toggle left vertical feed roller on/off (closed loop PID)
      controller.leftTrigger().toggleOnTrue(verticalFeedLeft.verticalFeedIntakeCommand());

      // Right Trigger = toggle right vertical feed roller on/off (closed loop PID)
      controller.rightTrigger().toggleOnTrue(verticalFeedRight.verticalFeedIntakeCommand());
    }

    if (intakeRollers != null) {
      // Right bumper = toggle intake rollers on/off
      controller.rightBumper().toggleOnTrue(intakeRollers.intakeCommand());
      // Left bumper = toggle outtake rollers on/off
      controller.leftBumper().toggleOnTrue(intakeRollers.outakeCommand());
    }

    if (intakePivot != null) {
      // D-pad Up = pivot to stow position (0 degrees)
      controller.povUp().onTrue(intakePivot.setDegreesCommand(0.0));
      // D-pad Down = pivot to deploy/intake position (145 degrees per design sheet)
      controller.povDown().onTrue(intakePivot.setDegreesCommand(145.0));
    }
  }

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    return autoChooser.get();
  }
}
